# Generated by Django 4.2.7 on 2023-12-15 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="uid",
            field=models.CharField(default=uuid.uuid4, max_length=40),
        ),
        migrations.DeleteModel(
            name="ListUser",
        ),
    ]
