# Generated by Django 4.2.6 on 2023-12-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_list_item_list"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ("id",)},
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(default=""),
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("list", "text")},
        ),
    ]
